name: Expresiones Avanzadas

on:
  workflow_dispatch:
    inputs:
      usuario:
        description: 'Nombre de usuario'
        required: true
        type: string
      pais:
        description: 'País de origen'
        required: true
        type: string
      permiso_especial:
        description: '¿Tiene permiso especial?'
        required: false
        type: boolean
        default: false

env:
  SALUDO: "Hola"
  PAISES_PERMITIDOS: '["España", "Mexico", "Colombia"]'

jobs:
  validar_y_saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Validar país
        id: validacion_pais
        run: |
          if ${{ contains(fromJSON(env.PAISES_PERMITIDOS), inputs.pais) }}; then
            echo "El país '${{ inputs.pais }}' está en la lista de permitidos."
            echo "::set-output name=pais_valido::true"
          else
            echo "El país '${{ inputs.pais }}' no está en la lista permitida."
            echo "::set-output name=pais_valido::false"
          fi
      
      - name: Saludar al usuario
        if: steps.validacion_pais.outputs.pais_valido == 'true'
        run: echo "${{ env.SALUDO }} ${{ inputs.usuario }}"
        
      - name: Mostrar permiso especial
        if: ${{ inputs.permiso_especial }}
        run: echo "El usuario ${{ inputs.usuario }} tiene permiso especial."
        
      - name: Mensaje de país no permitido
        if: steps.validacion_pais.outputs.pais_valido == 'false'
        run: echo "El país '${{ inputs.pais }}' no está en la lista permitida. No se puede continuar."
